import { z } from "zod";

const envSchema = z.object({
  // Public
  NEXT_PUBLIC_APP_URL: z.string().url().default("http://localhost:3000"),
  NEXT_PUBLIC_APP_NAME: z.string().default("Moment"),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url().optional(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1).optional(),
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: z.string().optional(),

  // Server only
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).default(""),
  DATABASE_URL: z.string().url().default("postgresql://localhost:5432/moment"),
  DATABASE_MIGRATION_URL: z.string().url().optional(),
  QSTASH_TOKEN: z.string().min(1).default(""),
  QSTASH_CURRENT_SIGNING_KEY: z.string().min(1).default(""),
  QSTASH_NEXT_SIGNING_KEY: z.string().min(1).default(""),
  STORAGE_PROVIDER: z.enum(["supabase", "r2"]).default("supabase"),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET: z.string().optional(),
  FEDAPAY_ENV: z.enum(["sandbox", "production"]).default("sandbox"),
  FEDAPAY_PUBLIC_KEY: z.string().min(1).default(""),
  FEDAPAY_SECRET_KEY: z.string().min(1).default(""),
  FEDAPAY_WEBHOOK_SECRET: z.string().min(1).default(""),
  FEDAPAY_WEBHOOK_SECRET_PREVIOUS: z.string().optional(),
  RESEND_API_KEY: z.string().min(1).default(""),
  EMAIL_FROM: z.string().email().default("noreply@moment.gift"),
  UPSTASH_REDIS_REST_URL: z.string().url().default("http://localhost:6379"),
  UPSTASH_REDIS_REST_TOKEN: z.string().min(1).default(""),
  SESSION_SECRET: z.string().min(32).default("default-secret-change-in-production-32chars!"),
  TURNSTILE_SECRET_KEY: z.string().optional(),
  DATA_ENCRYPTION_KEY: z.string().min(32).default("default-encryption-key-change-in-production-32chars!"),
  EMAIL_HMAC_KEY: z.string().min(32).default("default-hmac-key-change-in-production-32chars!"),
  CRON_SECRET: z.string().min(1).default("default-cron-secret-change-in-production"),
  GIFT_RETENTION_YEARS: z.string().transform(Number).pipe(z.number().int().positive()).default(5),
  SENTRY_DSN: z.string().url().optional(),
});

export const env = envSchema.parse({
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  DATABASE_URL: process.env.DATABASE_URL,
  DATABASE_MIGRATION_URL: process.env.DATABASE_MIGRATION_URL,
  QSTASH_TOKEN: process.env.QSTASH_TOKEN,
  QSTASH_CURRENT_SIGNING_KEY: process.env.QSTASH_CURRENT_SIGNING_KEY,
  QSTASH_NEXT_SIGNING_KEY: process.env.QSTASH_NEXT_SIGNING_KEY,
  STORAGE_PROVIDER: process.env.STORAGE_PROVIDER,
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
  R2_BUCKET: process.env.R2_BUCKET,
  FEDAPAY_ENV: process.env.FEDAPAY_ENV,
  FEDAPAY_PUBLIC_KEY: process.env.FEDAPAY_PUBLIC_KEY,
  FEDAPAY_SECRET_KEY: process.env.FEDAPAY_SECRET_KEY,
  FEDAPAY_WEBHOOK_SECRET: process.env.FEDAPAY_WEBHOOK_SECRET,
  FEDAPAY_WEBHOOK_SECRET_PREVIOUS: process.env.FEDAPAY_WEBHOOK_SECRET_PREVIOUS,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  SESSION_SECRET: process.env.SESSION_SECRET,
  TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
  DATA_ENCRYPTION_KEY: process.env.DATA_ENCRYPTION_KEY,
  EMAIL_HMAC_KEY: process.env.EMAIL_HMAC_KEY,
  CRON_SECRET: process.env.CRON_SECRET,
  GIFT_RETENTION_YEARS: process.env.GIFT_RETENTION_YEARS,
  SENTRY_DSN: process.env.SENTRY_DSN,
});

export type Env = z.infer<typeof envSchema>;
